version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github:
        patterns:
          - "*"

  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
    groups:
      gradle:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
