services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=delta
      - POSTGRES_PASSWORD=delta
      - POSTGRES_DB=delta
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
