apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: delta-backend
  namespace: delta
  labels:
    team: delta
spec:
  accessPolicy:
    inbound:
      rules:
        - application: delta-frontend
  image: {{image}}
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: db-f1-micro
        databases:
          - name: delta
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: true
  env:
    - name: DEV_MODE
      value: !!string "false"
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
