apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: delta-webhook-relay
  namespace: delta
  labels:
    team: delta
spec:
  image: {{image}}
  ingresses:
    - https://delta-webhook.nav.no
  accessPolicy:
    outbound:
      rules:
        - application: delta-backend
  resources:
    limits:
      memory: 32Mi
    requests:
      cpu: 10m
      memory: 32Mi
  replicas:
    max: 2
    min: 2
  port: 8080
  liveness:
    path: /health
    initialDelay: 5
    timeout: 5
    periodSeconds: 10
    failureThreshold: 6
  readiness:
    path: /health
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
