name: Deploy backend
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write # required for dep graph
      security-events: write # push sarif to github security
      id-token: write # required by gar 
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92
      - name: Run tests & build jar files
        run: ./gradlew test build
      - name: Build & push docker image to GAR
        uses: nais/docker-build-push@05dbb6091b30bd84279c6d64a45ef8782fd410a5
        id: docker-build-push
        with:
          team: delta
          pull: true
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@3f131e8634966bd73d06cc69884922b02e6faf92
      - name: Scan docker image for secrets
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          image-ref: '${{ steps.docker-build-push.outputs.image }}'
          format: 'sarif'
          scanners: 'secret'
          output: 'trivy.sarif'
      - uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e
        with:
          sarif_file: 'trivy.sarif'

  deploy-dev:
    name: Deploy to dev
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: build
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: nais/deploy/actions/deploy@5fdd91aaf69bb0d6dd5e5118cdacb639f487b93b
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais.yaml
          IMAGE: ${{ needs.build.outputs.image }}

  deploy-prod:
    name: Deploy to prod
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: [build, deploy-dev]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: nais/deploy/actions/deploy@5fdd91aaf69bb0d6dd5e5118cdacb639f487b93b
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais.yaml
          IMAGE: ${{ needs.build.outputs.image }}
