on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write # required for dep graph
      security-events: write # push sarif to github security
      id-token: write # required by gar 
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
    - uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'
    - uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2
    - name: Run tests & build jar files
      run: ./gradlew test build
    - name: Build & push docker image to GAR
      uses: nais/docker-build-push@v0
      id: docker-build-push
      with:
        team: delta
        pull: true
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2
    - name: Scan docker image for secrets
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8
      with:
        image-ref: '${{ steps.docker-build-push.outputs.image }}'
        format: 'sarif'
        scanners: 'secret'
        output: 'trivy.sarif'
    - uses: github/codeql-action/upload-sarif@5d4e8d1aca955e8d8589aabd499c5cae939e33c7
      with:
        sarif_file: 'trivy.sarif'

  deploy-dev:
    name: Deploy to dev
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: build
    steps:
      - uses: actions/checkout@v6
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais.yaml
          IMAGE: ${{ needs.build.outputs.image }}

  deploy-prod:
    name: Deploy to prod
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: [build, deploy-dev]
    steps:
      - uses: actions/checkout@v6
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais.yaml
          IMAGE: ${{ needs.build.outputs.image }}
