name: Deploy relay
on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Build & push docker image to GAR
        uses: nais/docker-build-push@be85229e81c0293c265c646c084f05317fb6e0d2
        id: docker-build-push
        with:
          team: delta
          pull: true
          docker_context: nginx-relay/
          image_suffix: relay
      - uses: nais/deploy/actions/deploy@823ec9b7e305ce7cf911d0f9a25f7da9d7486cf2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nginx-relay/nais.yaml
          IMAGE: ${{ steps.docker-build-push.outputs.image }}
