name: Deploy relay
on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Build & push docker image to GAR
        uses: nais/docker-build-push@078e460885ed0424b60d45ce9220b4be1748be9d
        id: docker-build-push
        with:
          team: delta
          pull: true
          docker_context: nginx-relay/
          image_suffix: relay
      - uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1
        env:
          CLUSTER: prod-gcp
          RESOURCE: nginx-relay/nais.yaml
          IMAGE: ${{ steps.docker-build-push.outputs.image }}
