name: Deploy relay
on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false
      - name: Build & push docker image to GAR
        uses: nais/docker-build-push@05dbb6091b30bd84279c6d64a45ef8782fd410a5
        id: docker-build-push
        with:
          team: delta
          pull: true
          docker_context: nginx-relay/
          image_suffix: relay
      - uses: nais/deploy/actions/deploy@c55d6073d913975d2dada508bdfefc6427d39867
        env:
          CLUSTER: prod-gcp
          RESOURCE: nginx-relay/nais.yaml
          IMAGE: ${{ steps.docker-build-push.outputs.image }}
